### ISSUE TITLE
Multiqc error

### ISSUE THREAD

**Issue by duyck** [Hoohm/dropSeqPipe#11]
Pipeline continually failed on multiqc report

Fix: Install multiqc development version 1.3
pip install git+https://github.com/ewels/MultiQC.git --user

Unnecessary Fix:
Double forward slash in pipeline does not seem to affect output however it looks weird...
[INFO   ]         multiqc : Searching '${HOME}/yourdirectory//logs'
Edit: __main__.py
Change: multiqc = 'multiqc -o {0} {0}/logs {0}/summary --force'.format(args.folder_path)
To: multiqc = 'multiqc -o {0} {0}logs {0}summary --force'.format(args.folder_path)

**Comment by Hoohm** [comment]
Hi and thanks for the heads up.
The next version won't be automatically generating the multiqc report although I still highly recommend it.

Best wishes

**Comment by Hoohm** [comment]
@duyck 
The new version actually integrates multiqc properly.
Closing this issue.
