### ISSUE TITLE
SyntaxError in line 7 of Snakefile

### ISSUE THREAD

**Issue by amufaamo** [Hoohm/dropSeqPipe#117]
Hi, I try to run dropSeqPipe, but I got error

`snakemake --cores 8 qc --e-conda --directory /dropSeqPipe/working_dir/
`
```
SyntaxError in line 7 of /dropSeqPipe/Snakefile:
invalid syntax
```

line 7 of Snakefile is singularity: is something wrong?

```
import pandas as pd
import os
import re
import glob
from snakemake.utils import validate, min_version

singularity:
    "shub://seb-mueller/singularity_dropSeqPipe:v04"

min_version("5.1.2")
```

**Comment by NogitoErgoSum** [comment]
Got the same error

**Comment by NogitoErgoSum** [comment]
I think it's got to do with snakemake version. I was using 'bioconda/linux-64::snakemake-3.13.3-py36_0' that I installed using conda by following the installation documentation. 

After deactivating the environment and using the system snakemake (version 6.6.1) it worked. Well it kind of worked, now it says I don't have mamba package manager but that is probably another issue.

**Comment by amufaamo** [comment]
OK, I will re-install snakemake. I try it now.

**Comment by amufaamo** [comment]
Thank you it worked!! but I got new error. Close this issue, and build new issue. Thank you so much
