### ISSUE TITLE
STAR: terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by pwl** [Hoohm/dropSeqPipe#17]
I encountered this issue https://github.com/alexdobin/STAR/issues/103 when running dropSeqPipe in the `meta` mode.  Would it be possible to add the `--genomeChrBinNbits` parameter to your pipeline?  After running the same STAR command but with `--genomeChrBinNbits 15` everything went fine.

**Comment by pwl** [comment]
Also, it's not a big deal but `--runThreadN` option ignores the `--cores` value when running in the `meta` mode https://github.com/Hoohm/dropSeqPipe/blob/c8e70ce39cf8ce46638e85906b43fb479e2688e3/rules/generate_meta.smk#L85

EDIT: now I see how it works (allocating tasks according to how many threads they are defined to use).  Please ignore that comment:-)

**Comment by Hoohm** [comment]
Hello,
I can expose this value, no problem.
It will be done in the next release (maybe 1 or 2 weeks).
In the meantime you can easily edit it manually in the rule.

Concerning the number of threads = 4 for the INDEX generation, I ran into performance issue when using a high number of threads a couple of months ago, hence the limit to 4. Maybe this has been fixed now in STAR. I'll test it out and maybe change it to a higher value.

**Comment by Hoohm** [comment]
Hello @pwl 
I changed it up a bit, in the next version will calculate the value with the proposed function in [the issue](https://github.com/alexdobin/STAR/issues/103).

**Comment by pwl** [comment]
@Hoohm thanks for your comments.

So far nothing changed in the `generate_meta.smk`, I guess you haven't pushed the changes yet?

I tested STAR with more threads (8) and it seems to run just fine but that's just my limited experience.

**Comment by Hoohm** [comment]
@pwl That is right, haven't pushed anything yet.
I'm gonna test STAR again later, but that's not gonna be a priority and I guess it's not much a bottleneck right now since it only runs once per read size.

**Comment by pwl** [comment]
Nah, the index generation runs fine with 4 threads, so that's not critical by any means.  I'll keep an eye on the new releases, currently I just keep a modified `generate_meta.smk` locally.

Oh, and by the way, I saw the changelog file and there are release numbers there but there are no git tags to reflect these releases (aside from v0.24).  I know this is an unrelated issue but could you please bring back these tags with the upcoming releases?

**Comment by Hoohm** [comment]
Yea, I have to force myself to make releases. It's planned for the next release, 0.31

**Comment by pwl** [comment]
Thanks for all the help, I think I can close this issue now.
