### ISSUE TITLE
MinCellFraction parameter to estimate STAMP count from config.yaml disappeared

### ISSUE THREAD

**Issue by seb-mueller** [Hoohm/dropSeqPipe#18]
I've noticed the automatic determination of STAMPS in was taken out from v0.23.
I.e. the following line, which depended on the the cell fraction (`MinCellFraction = 0.001` or so in `config.yaml`) parameter (at least this what I think hapend, please correct my if I'm wrong):

https://github.com/Hoohm/dropSeqPipe/blob/2fe6b2ac95906427116ece31b7582af748e9ead1/dropSeqPipe/Rscripts/singleCell/knee_plot.R#L19

This has always been a bit mysterious to me, nevertheless one could have the number of STAMPs estimated (semi)-automatically I was wondering why this has taken out (at least this what I think happened, please correct my if I'm wrong)? 
Are there any plans to automatize this step again? 

------
Unrelatedly (not sure this sort deserves an issue by itself)
One other minor comment is it the location of the Snakefile should be discussed in the wiki.

I.e. the commands [here](https://github.com/Hoohm/dropSeqPipe/wiki/Running-dropSeqPipe#running-the-pipeline-tldr-version) assumes to have the `Snakefile` in the project directory (root folder containing the experiment).

This has to be done manually for each project, so I'd include in the wike something like:

Snakefile which ships with dropSeqPipe needs to be copied or linked into the each project directory, i.e.

    ln -s /installpath/dropSeqPipe/Snakefile .

or

    cp -s /installpath/dropSeqPipe/Snakefile .

or specified as parameter:

    snakemake --snakefile /installpath/dropSeqPipe/Snakefile --cores 8 qc

**Comment by Hoohm** [comment]
Hello! @seb-mueller 

The automatic determination has been taken because I've never found a full proof way to do it.
This might come back later if I find something that's robust. I've also noticed that later in the analysis, I tend to filter out based on other criteria (percent mitochondrial genes, percent of reads taken up by the top 50 genes per cell, etc..) I always tend to filter more than the auto filtering that was proposed via the knee plot. There are a few [ideas](https://cgatoxford.wordpress.com/2017/05/23/estimating-the-number-of-true-cell-barcodes-in-single-cell-rna-seq-part-2/) that might provide a good way to do it. I have to dig into it a bit more.

The MinCellFraction wasn't useful either because it was kind of similar to the number of expected cells, although it did take into account the total number of reads.

For now, for practical and ease of use reasons, I would just use the amount of cells you expect and use other filters downstream.

About the Snakefile in the experiment, you are correct, I should add something in the wiki. The next update (this week probably) will account for batches in the same experiment. I'll ad something in the wiki to provide more context as to how you can use it.

**Comment by Hoohm** [comment]
@seb-mueller 
I'm open to suggestions. If you use a method you trust, I'd gladly try it out.

**Comment by seb-mueller** [comment]
Thanks for the clearing this up. I agree with your reasoning, this method probably wasn't robust enough to grantee a decent estimate.
The blog post you mentioned is an interesting read, mostly focusing on error correction which they concluded isn't even worth doing at the end ;) 

As a suggestion, I'd probably leave it to the user to specify the count, however the knee-plot should nevertheless show an automatic estimate and report it. The user could than manually change the number to this estimate if it seems reasonable. In fact I could imagine having various estimates reported based on different methods.   

As for appropriate method(s), the ones from the blog could be used, but they seem to focus on error correction and might have to be part of preprocessing. 
As for determining the knee itself, I haven't looked into this issue in depth, but I feel this must be a researched problem with caned solutions. A quick search pointed me to [this article](http://dx.doi.org/10.1109/ICDCSW.2011.20) for instance. 
I'll have another look and might even send a pull request or so. Anyway nice piece of software so far!

**Comment by Hoohm** [comment]
Sorry, this was the second part of the article. The [first part](https://cgatoxford.wordpress.com/2017/05/18/estimating-the-number-of-true-cell-barcodes-in-single-cell-rna-seq/) talking about this "true" stamps is about the selection

There is a "report" with the knee plot. It will show you where you cut anyways so you have a rough idea of how much of the reads you keep.

I'm still working a few raw stats reports/plots right now, and some might actually benefit from an estimate. Typically, the base frequency plot needs a list of barcodes that are valid, this is why it's not available anymore for now. I could then, propose a cutoff to the user, which can accept it or not. Maybe the default would provide the count matrix based on the one I found and an advanced version would let you choose.

I think the knee is really a "bad" idea as to how to find the limit. Complicated to find where this bend is and sometimes you don't even have one.

A simple one which I'm testing right now is this top50 genes. If I'm not mistaken, this should always look like a binomial distribution with the minimum in between the two peaks being a reasonable cut. But it still requires some testing.

It should come up again on the CHANGELOG.

Glad you the package. :)

**Comment by seb-mueller** [comment]
I've in fact read this already (I didn't make this clear), his proposed knee method might be a obvious potential choice:

> ... I initially attempted to identify the inflection point by fitting a spline function to the cumulative frequency but quickly realised it was much easier to work from the distribution of counts (log10) per cell barcode (Figure 3). Here the inflection point is represented by the local minima between the distribution of counts for ‘true’ and ‘false’ barcodes.

Although Tom Smith seems to have come up with this and might not be robust or thoroughly tested.  Again, I feel there must be something out there. 
Anyway, I suppose something like in Fig 3 could be a good addition to the knee plot, i.e. `distribution of counts (log10)` to visually assess the local minima.
If you want I could get me hand dirty on this (i.e. tinkering with the `know_plot.r`)?

**Comment by Hoohm** [comment]
Ok, sorry :P

I'm open to any help man! If you want to get dirty, be my guest. Shouldn't be that hard to add theplot beneath the knee plot like I did for rna_metrics for example.

**Comment by seb-mueller** [comment]
Ah, only read the second part of your answer. My notification mail only had a fraction of it in it for some reason. Anyway, totally agree. curious how the "top50 genes" approach pans out. Do you have a reference to this general approach? Just curious.

**Comment by Hoohm** [comment]
No reference, an idea from a co-worker.
You could translate that by "diversity coefficient". If you have a "normal" amount of reads in your cell compared to others but all of them are only in 50 genes instead of spreading to a few hundreds/thousands, most of the time, it's a "bad" cell. Most of the time it correlates with high mitochondrial content which probably means your cell was dead or "open" before capturing.

There is a paper talking about a fluidigm C1 run where they had visual confirmation of dead cells correlating with high mitochondrial content.

**Comment by seb-mueller** [comment]
Hi @Hoohm, I've finally found some time extend the knee plot.

It's basically adding more panel to visually guide a manual selection by suggesting possible cutt-offs based on the maximum of the 2nd derivative (loess smoothed) of the reads-count for each barcode.
That's basically what I've gathered to be most robust from various sources. It should be rather obvious from looking at the plot and the code. 

I've put it into the branch "seb03" on my fork, not sure if it should be a PR at this stage, just wanted to check what you think? Only the [plot_knee_plot.R](https://github.com/seb-mueller/dropSeqPipe/blob/seb03/scripts/plot_knee_plot.R) script has changed anyway. Below is an example plot of one of the Macosko dataset, the highest local maximum (643 STAMPS is close to what is believed to be around 570 STAMPS, but this can probably still be optimized or debugged):

![Imgur](https://i.imgur.com/FQafKVc.png)

**Comment by Hoohm** [comment]
This looks cool!
I'll try it on my SCBR-seq data. It should find exactly 96 cells and post it.

I'm planning a few more things and might publish the pipeline in the future. So if you want to join in, this could be a good contribution. (this is what you meant by PR?)

**Comment by seb-mueller** [comment]
Glad you like it! 
It's might still have a few glitches and might not be the best approach but seems to be a decent path to go done having done some reading.

I'd be happy to be on board and in fact was planing to extend a few more things such as a violine plot and some sort of bead saturation etc.. If you want to discuss, best to use email or so, my details are [here](https://www.plantsci.cam.ac.uk/directory/mueller-sebastian).

I meant that I havent issue a PR (Pull request) for feed back to your repository, but could do this if you think it's usefull.
