### ISSUE TITLE
sample_yaml' is not defined

### ISSUE THREAD

**Issue by abmmki** [Hoohm/dropSeqPipe#2]
Hi,

 I am using latest version of the Dropseq pipeline. (installed today)

However, I am getting following error.  I have the config.ymal file. It is in the right directory.
So, how can I overcome this? Could you help?

dropSeqPipe -f /hd2 -c /home/bin/DropSeqPipelineHoohm_v0.23a/dropSeqPipe/local.yaml -m pre-process --rerun

Traceback (most recent call last):
  File "/bin/dropSeqPipe", line 9, in <module>
    load_entry_point('dropSeqPipe==0.23a0', 'console_scripts', 'dropSeqPipe')()
  File "/home/bin/DropSeqPipelineHoohm_v0.23a/dropSeqPipe/dropSeqPipe/__main__.py", line 96, in main
    if(sample_yaml['GLOBAL']['data_type'] not in ['singleCell', 'bulk']):
NameError: name 'sample_yaml' is not defined

**Comment by abmmki** [comment]
OK, I see the problem, There is a typo in the __main__.py file
# it should be 
samples_yaml = yaml.load(samples_config)

# instead of 

sample_yaml = yaml.load(samples_config)

(samples vs sample)

# so, after editing this, re run the setup file

**Comment by Hoohm** [comment]
Hello @abmmki and thanks a lot for the notice.
It's fixed now.
