### ISSUE TITLE
InputFunctionException in line 5 /rules/map.smk

### ISSUE THREAD

**Issue by olechnwin** [Hoohm/dropSeqPipe#23]
Hi,

I cannot figure out how to fix this error:

InputFunctionException in line 5 of /rules/map.smk:
KeyError: 'the label [sample1_N706_S2_L001_MOUSE] is not in the [index]'
Wildcards:
sample=sample1_N706_S2_L001_MOUSE

I've ran snakemake  --cores 12 qc filter map and it ran to completion.
Then, the above error happen when running: snakemake --cores 12 split_species extract_species

here is my config.yaml:
LOCAL:
    TMPDIR: ~/tmp
    DROPSEQ-wrapper: opt/Drop-seq_tools-1.13/drop-seq-tools-wrapper.sh
    MEMORY: 32g
META:
    species:
        - HUMAN
        - MOUSE
    species_ratio: 0.20
    reference_file: hg19_mm10_transgenes.fasta 
    annotation_file: hg19_mm10_transgenes.gtf
    reference_folder: opt/dropSeqPipe/ref
FILTER:
    IlluminaClip: NexteraPE-PE.fa
    5PrimeSmartAdapter: GCCTGTCCGCGGAAGCAGTGGTATCAACGCAGAGTAC
    Cell_barcode:
        start: 1
        end: 12
        min_quality: 30
        num_below_quality: 0
    UMI:
        start: 13
        end: 20
        min_quality: 30
        num_below_quality: 0
EXTRACTION:
    bc_edit_distance: 0
    min_count_per_umi: 1
STAR_PARAMETERS:
    outFilterMismatchNmax: 10
    outFilterMismatchNoverLmax: 0.3
    outFilterMismatchNoverReadLmax: 1
    outFilterMatchNmin: 0

**Comment by Hoohm** [comment]
Hello @olechnwin 
This is a known bug and I'm working on it.
I have a testing fix. Can you try to add those lines to the `Snakefile` file:
```
wildcard_constraints:
    sample="({})".format("|".join(samples.index))
```

Tell me if it works

**Comment by olechnwin** [comment]
Hi @Hoohm 
Where should I put those lines? under rule split_species?

update:
looks like the above fix works when I put it below read_lengths line.

**Comment by Hoohm** [comment]
@olechnwin Great news!

This will be added in the next release.
Can this issue be closed?
