### ISSUE TITLE
advice on knee plot

### ISSUE THREAD

**Issue by olechnwin** [Hoohm/dropSeqPipe#25]
Although this is not issue on running dropSeq pipeline, however, since the wiki has explanation for the knee plot, I thought I'll post it here in hope of getting advice.

This is the second run of DropSeq that we've analyzed and both times my knee plots never show a clear bend (see attached).
[knee_plot.pdf](https://github.com/Hoohm/dropSeqPipe/files/1820280/knee_plot.pdf)
What is your advice for this? Thanks!

**Comment by Hoohm** [comment]
Hello @olechnwin 
From my experience the knee plot is just "bad" for true STAMP selection.

For now I just leave this as is and propose people to use other selection methods that rely more on metadata variables [see example](https://bioinformatics.stackexchange.com/questions/3232/improve-scrna-seq-dataset-for-further-analysis/3258#3258) than "simple" counts statistics.

I can suggest you a good read [here](https://cgatoxford.wordpress.com/2017/05/18/estimating-the-number-of-true-cell-barcodes-in-single-cell-rna-seq/) regarding true STAMP selection.

0.31 will still not propose a new method but check out the new branches that will come up just after the new release and you'll find some new features for true STAMP selection.

I hope this helps out a bit.


We are still thinking about the best way to implement it but for now, this is the best I can give you.

**Comment by seb-mueller** [comment]
Further to what Patrick has said, we were in fact discussing something similar in issue #18 (especially towards the end).
I've implemented a slightly more informative knee-plot on this [branch](https://github.com/seb-mueller/dropSeqPipe/tree/seb03). If you are keen you are welcome to try it out, I'd be curious on any feedback.

**Comment by olechnwin** [comment]
Thank you @Hoohm  for your response. I'll try the selections that you suggested in stackexchange.
@seb-mueller, thanks for letting me know. I'll let you know my feedback after I tried your knee-plot.
