### ISSUE TITLE
high % mixed species?

### ISSUE THREAD

**Issue by olechnwin** [Hoohm/dropSeqPipe#27]
Apologize for posting all these questions if I'm not supposed to. I found I have more useful answers/responses by posting in this github rather than the group.

I am attaching our mixed species plot. As you can see there are about 21% mixed species. I used the default 80% purity threshold. I know in the wiki plot, the mixed species is about 15%. In one of the post in dropseq google group, Evan mentioned that 6-9% species mixing is relatively high (corresponds to 12-18% overall contamination rate). Should I be concerned with the quality of our experiment? Any suggestions? Thanks again for your help!
[species_plot_genes.pdf](https://github.com/Hoohm/dropSeqPipe/files/1825505/species_plot_genes.pdf)

**Update:** just realized the second sample only has ~10% of human cells
[sample2_species_plot_genes.pdf](https://github.com/Hoohm/dropSeqPipe/files/1825626/sample2_species_plot_genes.pdf)

**Comment by Hoohm** [comment]
@olechnwin 
The main purpose of the `issues` tab is there for issues related to the code and the usage of the pipeline. Although it is not yet clearly stated where result linked question should be added, it will be in the future.

The next iteration (post 0.31) will propose a way to upload/share those plots as well as integrate a short README illustrating the protocol. If you are interested to help us out as well as the community, we will be looking for participants for this platform.

This will be the main way to exchange and troubleshoot this kind of questions and issues.

For now, I would still advise to use the google mailing list as you will find more wetlab people there.

I can tell you from this plot that you have a high rate of doublet cells, but I have no clue as to why, sorry.

**Comment by olechnwin** [comment]
@Hoohm, that's what I thought. Thanks for confirming the high doublet cells. That's somehow useful. I wished the google group is more responsive.

**Comment by Hoohm** [comment]
@olechnwin I hope the new platform will provide the community with a lot of hints and answers :)
