### ISSUE TITLE
keyError

### ISSUE THREAD

**Issue by abmmki** [Hoohm/dropSeqPipe#3]
Hi

can you help to solve the following problem. I am using latest version 0.23a

**dropSeqPipe -f /hd2/ -c /home/dropSeqPipe/local.yaml -m pre-process**

[Tue Sep 19 09:00:33 CDT 2017] picard.sam.SamToFastq done. Elapsed time: 16.92 minutes.
Runtime.totalMemory()=1126170624
[Tue Sep 19 09:00:33 2017] Finished job 1.
[Tue Sep 19 09:00:33 2017] 3 of 4 steps (75%) done
[Tue Sep 19 09:00:33 2017] 
[Tue Sep 19 09:00:33 2017] localrule all:
    input: wts3_tagged_unmapped.fastq.gz
    jobid: 0
[Tue Sep 19 09:00:33 2017] 
[Tue Sep 19 09:00:33 2017] Finished job 0.
[Tue Sep 19 09:00:33 2017] 4 of 4 steps (100%) done
Running Alignement
[Tue Sep 19 09:00:33 2017] **KeyError** in line 23 of /usr/lib/python3.4/site-packages/dropSeqPipe/Snakefiles/singleCell/star_align.snake:
'allowed_aligner_mismatch'
  File "/usr/lib/python3.4/site-packages/dropSeqPipe/Snakefiles/singleCell/star_align.snake", line 23, in <module>
Plotting STAR logs
Error in file(file, "rt") : cannot open the connection
Calls: star.logs -> read.table -> file
In addition: Warning message:
In file(file, "rt") : cannot open file 'NA': No such file or directory
Execution halted
Traceback (most recent call last):
  File "/bin/dropSeqPipe", line 9, in <module>
    load_entry_point('dropSeqPipe==0.23a0', 'console_scripts', 'dropSeqPipe')()
  File "/usr/lib/python3.4/site-packages/dropSeqPipe/__main__.py", line 150, in main
    shell(star_summary)
  File "/usr/lib/python3.4/site-packages/snakemake-3.10.1-py3.4.egg/snakemake/shell.py", line 80, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'Rscript /usr/lib/python3.4/site-packages/dropSeqPipe/Rscripts/STAR_log_plot.R /hd2/' returned non-zero exit status 1

**Comment by Hoohm** [comment]
Hello,

you probably have a mispelling in the config.yaml from the run.
Can you double check the spelling?
`allowed_aligner_mismatch`
