### ISSUE TITLE
Error in creating annotation.refFlat

### ISSUE THREAD

**Issue by KaiWu-Umich** [Hoohm/dropSeqPipe#34]
Hi there. 
Thanks a lot for building up this wonderful package which greatly helped biologist with limited basis for coding like me. 

I am trying to run my first test sample, but I met this error: 

> Error in rule create_refFlat:
>         jobid: 51
>         output: /home/coffeelover/NGStools/Reference_Files/annotation.refFlat
> 
> RuleException:
> CalledProcessError in line 51 of /home/coffeelover/sc-experiment/4-cell-lines/dropSeqPipe/rules/generate_meta.smk:
> Command ' set -euo pipefail;  /home/coffeelover/NGStools/Drop-seq_tools-1.13 -m 80g -p ConvertToRefFlat		ANNOTATIONS_FILE=/home/coffeelover/NGStools/Reference_Files/annotation.gtf		OUTPUT=/home/coffeelover/NGStools/Reference_Files/annotation.refFlat		SEQUENCE_DICTIONARY=/home/coffeelover/NGStools/Reference_Files/genome.dict ' returned non-zero exit status 126.
>   File "/home/coffeelover/sc-experiment/4-cell-lines/dropSeqPipe/rules/generate_meta.smk", line 51, in __rule_create_refFlat
>   File "/home/coffeelover/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run

I downloaded GTF from Ensembl and re-named as annotation.gtf as required. I am not sure what exactly caused this error nor how to troubleshoot it. Could you please help me with this issue?

Thanks a million,
Kai

**Comment by Hoohm** [comment]
Hello @KaiWu-Umich 
I would need the error message from the tool and not the one from snakemake.

What species are you using? There are some known issues with arabidopsis.

**Comment by Hoohm** [comment]
Closing this for now, feel free to reopen
