### ISSUE TITLE
Question: should this be fastx, no fatsx ?

### ISSUE THREAD

**Issue by colindaven** [Hoohm/dropSeqPipe#36]
rules/map.smk

17 | 'data/{sample}/Log.final.out'
-- | --
18 | params:
19 | extra="""--outReadsUnmapped Fatsx\
20 | --outFilterMismatchNmax {}\

**Comment by Hoohm** [comment]
Hello @colindaven 

You are totally right! That might explain why it didn't work.
I didn't look more into it at the time and forgot I wanted to implement that.
Nice catch, thanks :)

**Comment by colindaven** [comment]
Nice, glad I could help. Thanks for the pipeline, it's very useful so far.

**Comment by Hoohm** [comment]
Glad it helps out :)
If you're missing any features, don't hesitate to make an issue or propose a pull request
