### ISSUE TITLE
sjdbOverhang Error

### ISSUE THREAD

**Issue by abmmki** [Hoohm/dropSeqPipe#4]
Hi,
I have attached the screen-shot of error logs 
Could you please help.

thanks
![error](https://user-images.githubusercontent.com/7769806/30656112-c6635248-9e54-11e7-80d7-6ec2e618e222.png)

**Comment by Hoohm** [comment]
Hello,
this is because the new version uses non annotated STAR index to do the mapping with an overhang specific to the sample.
So when you give it an already annotated index, it won't run because the overhang is not compatible.
To make it run, you have to erase the old STAR index and run the generate-reference again.
The easiest way would be to just erase all the files in the reference folder except the genome.fa and the annotation.gtf and rerun it.
Let me know if it works.

**Comment by abmmki** [comment]
Hi,

I actually used re-generated metadata. I got following files there and a folder (with files) "STAR_INDEX_NO_GTF". (although I am using "STAR_INDEX" folder in config.ymal file as METAREF:) However, when I run the command of "generate-meta", I got an error message even after job complete 100% signal.

dmel.6.9.consensus_introns.intervals
dmel.6.9.dict
dmel.6.9.exons.intervals
dmel.6.9.fa
dmel.6.9.genes.intervals
dmel.6.9.gtf
dmel.6.9.intergenic.intervals
dmel.6.9_reduced.gtf
dmel.6.9.refFlat
dmel.6.9.rRNA.intervals
Log.out

STAR_INDEX_NO_GTF
chrLength.txt
chrNameLength.txt
chrName.txt
chrStart.txt
Genome
genomeParameters.txt
SA
SAindex

**# Command:** and **Error**

dropSeqPipe -f /home/dmel6_gfp -c /home/bin/DropSeqPipelineHoohm_v0.23a/dropSeqPipe/local.yaml -m generate-meta

[Thu Sep 21 08:19:28 CDT 2017] org.broadinstitute.dropseqrna.annotation.CreateIntervalsFiles SEQUENCE_DICTIONARY=dmel.6.9.dict REDUCED_GTF=dmel.6.9_reduced.gtf OUTPUT=. PREFIX=dmel.6.9    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json
[Thu Sep 21 08:19:28 CDT 2017] Executing as khademul@10-119-128-11.cpb.uic.edu on Linux 4.8.13-100.fc23.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_111-b16; Picard version: 1.12(d3aeea7_1452606774) IntelDeflater
[Thu Sep 21 08:19:29 CDT 2017] org.broadinstitute.dropseqrna.annotation.CreateIntervalsFiles done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=1914175488
[Thu Sep 21 08:19:29 2017] Finished job 1.
[Thu Sep 21 08:19:29 2017] 5 of 6 steps (83%) done
[Thu Sep 21 08:19:29 2017] 
[Thu Sep 21 08:19:29 2017] localrule all:
    input: dmel.6.9.rRNA.intervals, STAR_INDEX_NO_GTF/SA
    jobid: 0
[Thu Sep 21 08:19:29 2017] 
[Thu Sep 21 08:19:29 2017] Finished job 0.
[Thu Sep 21 08:19:29 2017] 6 of 6 steps (100%) done

Traceback (most recent call last):
  File "/bin/dropSeqPipe", line 9, in <module>
    load_entry_point('dropSeqPipe==0.23a0', 'console_scripts', 'dropSeqPipe')()
  File "/usr/lib/python3.4/site-packages/dropSeqPipe/__main__.py", line 96, in main
    if(samples_yaml['GLOBAL']['data_type'] not in ['singleCell', 'bulk']):
UnboundLocalError: local variable 'samples_yaml' referenced before assignment

# following is the config file:

Samples:
    wts3:
        fraction: 0.001
        expected_cells: 2000
GENOMEREF: /home/DropSeqMetaData/dmel.6.9.fa
REFFLAT: /home/DropSeqMetaData/dmel.6.9.refFlat
METAREF: /home/DropSeqMetaData/STAR_INDEX
RRNAINTERVALS: /home/DropSeqMetaData/dmel.6.9.rRNA.intervals
GTF: /home/DropSeqMetaData/dmel.6.9.gtf
SPECIES:
    - DROSOPHILA
GLOBAL:
    5PrimeSmartAdapter: AAGCAGTGGTATCAACGCAGAGT
    data_type: singleCell
    allowed_aligner_mismatch: 10
    min_count_per_umi: 1
    Cell_barcode:
        start: 1
        end: 12
        min_quality: 10
        num_below_quality: 1
    UMI:
        start: 13
        end: 20
        min_quality: 10
        num_below_quality: 1

# could you help on what I am missing this time

**Comment by Hoohm** [comment]
Hello,
your reference files are fine. The bug came from a indentation error in the code.
It's fixed now (pushed) but was only present for `generate-meta`

You can run the rest with the reference files you have normally.

**Comment by abmmki** [comment]
Hi,

Many thanks. However, it required folder name to be "STAR_INDEX_NO_GTF" in stead of what says in the wiki "STAR_INDEX" . Otherwise file not found error showed.
thanks

**Comment by Hoohm** [comment]
Perfect!
I think I'll leave the path like this for now. the STAR index is a general name for any path you got. People might actually create their own index without using `generate-meta`.
In the future it will be automated and this path won't be manually named anymore.
I close this issue then.
Thank you
