### ISSUE TITLE
Pipeline stops when it start making R plots

### ISSUE THREAD

**Issue by terooatt** [Hoohm/dropSeqPipe#40]
Hi,

Dropseqpipe worked well for me couple months ago but recently after I have updated it it keeps on stoping when it starts using the Rscripts. It looks like some conda environments are incompatible with some R libraries such ggplot2, I think. Anyways here is the error I get, can you help. Thank you very much.

localrule plot_BC_drop:
    input: logs/Human_mouse_0.25M_CELL_barcode.txt, logs/Human_mouse_0.25M_UMI_barcode.txt, logs/Human_mouse_0.25M_reads_left.txt, logs/Human_mouse_0.25M_reads_left_trim.txt
    output: plots/BC_drop.pdf
    jobid: 22

Activating conda environment: /home/tommy/Nadia5_mix_human_mouse/dropSeqPipe/.snakemake/conda/122c4b70
Activating conda environment: /home/tommy/Nadia5_mix_human_mouse/dropSeqPipe/.snakemake/conda/122c4b70
    Error in rule plot_yield:
        jobid: 31
    Error in rule plot_BC_drop:
        output: plots/yield.pdf
        jobid: 22
        conda-env: /home/tommy/Nadia5_mix_human_mouse/dropSeqPipe/.snakemake/conda/122c4b70
        output: plots/BC_drop.pdf

        conda-env: /home/tommy/Nadia5_mix_human_mouse/dropSeqPipe/.snakemake/conda/122c4b70

RuleException:
CalledProcessError in line 165 of /home/tommy/Nadia5_mix_human_mouse/dropSeqPipe/rules/map.smk:
Command 'source activate /home/tommy/Nadia5_mix_human_mouse/dropSeqPipe/.snakemake/conda/122c4b70; set -euo pipefail;  Rscript /home/tommy/Nadia5_mix_human_mouse/dropSeqPipe/scripts/.snakemake.fx15wxlz.plot_yield.R ' returned non-zero exit status 1.
  File "/home/tommy/Nadia5_mix_human_mouse/dropSeqPipe/rules/map.smk", line 165, in __rule_plot_yield
  File "/home/tommy/miniconda3/envs/dropSeqPipe/lib/python3.6/concurrent/futures/thread.py", line 55, in run
RuleException:
CalledProcessError in line 258 of /home/tommy/Nadia5_mix_human_mouse/dropSeqPipe/rules/filter.smk:
Command 'source activate /home/tommy/Nadia5_mix_human_mouse/dropSeqPipe/.snakemake/conda/122c4b70; set -euo pipefail;  Rscript /home/tommy/Nadia5_mix_human_mouse/dropSeqPipe/scripts/.snakemake.7qdvqpqr.plot_BC_drop.R ' returned non-zero exit status 1.
  File "/home/tommy/Nadia5_mix_human_mouse/dropSeqPipe/rules/filter.smk", line 258, in __rule_plot_BC_drop
  File "/home/tommy/miniconda3/envs/dropSeqPipe/lib/python3.6/concurrent/futures/thread.py", line 55, in run
Removing temporary output file data/Human_mouse_0.25M/Aligned.out.bam.
Finished job 57.

**Comment by Hoohm** [comment]
Hello.
Thanks for the report.
I actually updated the env for ggplot2 a couple of hours ago.
Try it with the new one.
I think it came with the ggplo2 3.0 update.
Now ggplot2 is fixed and I've added the missing fortranlib.

To be in the safe side, I would delete the plot env so that it downloads it
from scratch.

If you still have issues after the update, could you please add the
logfiles that show the R error and not the snakemake log.

Thank you

**Comment by terooatt** [comment]
Ok great, it worked. Thanks a lot.
