### ISSUE TITLE
Modern August 2018 conda - issues 

### ISSUE THREAD

**Issue by colindaven** [Hoohm/dropSeqPipe#45]
As you probably know, conda has changed a lot recently. 

```
conda activate single_cell
snakemake --use-conda --cores 16
```

I experienced this error : which conda
conda could not be found

After entering the following within the conda env, the pipeline can find conda again. I.e. conda does not seem to be installed by default within a conda env, at least for me.

`conda install conda`

**Comment by Hoohm** [comment]
Hey @colindaven 
I've never experienced this before.
Although, I don't use the "activation" of env anymore since Snakemake does that for each rule now.

Good tip though might help people with a similar issue :)

can I close it?
