### ISSUE TITLE
Exception in thread "main" picard.PicardException: In paired mode, read name 1  does not match read name 2 

### ISSUE THREAD

**Issue by Hofphi** [Hoohm/dropSeqPipe#48]
Hi there,
thanks for this nice package and the good documentation. I was trying to run the first analysis with dropSeqPipe but encountered an error that lead to abruption of the pipeline.

The Snakemake error output is the following: 

'Exception in thread "main" picard.PicardException: In paired mode, read name 1 (NB501971:102:HC355BGX5:1:11101:15471:1050) does not match read name 2 (NB501971:102:HC355BGX5:2:11101:19695:1043)
        at picard.sam.FastqToSam.getBaseName(FastqToSam.java:446)
        at picard.sam.FastqToSam.doPaired(FastqToSam.java:338)
        at picard.sam.FastqToSam.makeItSo(FastqToSam.java:309)
        at picard.sam.FastqToSam.doWork(FastqToSam.java:282)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:268)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)
[Sun Sep 30 01:42:05 2018]
Error in rule fastq_to_sam:
    jobid: 38
    output: data/rat_data_N705_unaligned.bam
    conda-env: /scratch/hofphi00/dropSeqPipe/.snakemake/conda/a5697629'

I would really much appreciate your help on this. Please let me know if you need something else in order to understand my issue.

**Comment by Hoohm** [comment]
Hello @Hofphi 

I'm glad you enjoy the pipeline :)

From what I gather, you have a mismatch between R1 and R2.

If I had to guess, there was a filtering step on your data before running dropSeqPipe.
This means you have some reads from R1 missing in R2 (or vice-versa).

I have three solutions for you.
1) Go back to the rawer data and run with that.
2) use the develop branch of dropSeqPipe. Only working with a whitelist of barcodes. 10x, scrbseq, etc
3) use bbmap to reconcile the files with this command: `repair.sh -Xmx{params.memory} in={input.R1} in2={input.R2} out1={output.R1} out2={output.R2} repair=t threads={threads}`

Let me know if that works or if you need any other help :)

**Comment by Hoohm** [comment]
Hello @Hofphi 
I haven't heard back from you. Did you find the problem?

**Comment by Hofphi** [comment]
Hello @Hoohm,

I have some problems with the server cluster right now and couldn't run the pipeline yet but I think my problem occurred when I concatenated the files raw sequencing data. We sequence on a illuminati device and get four digital lanes four the paired end reads, so four for R1 and four for R2. I must have concatenated them in the wrong order or something. 
I will give you an update as soon as ran the pipeline!

**Comment by Hofphi** [comment]
Hello @Hoohm 
definitely did something wrong when I concatenated the raw sequencing data. I generated a new joined-file and then everything was working
