### ISSUE TITLE
'repair' rule: too many threads declared?

### ISSUE THREAD

**Issue by grst** [Hoohm/dropSeqPipe#49]
the `'threads': 28` in the `repair` rule from the develop branch made the entire pipeline run sequentially. 
The rule appears by far not to use the 28 threads (rather 2-6 on average). 

Maybe adjust that.

**Comment by Hoohm** [comment]
Thanks for the catch :+1:

**Comment by grst** [comment]
Actually, the same applies for star_map...
For me it turned out to be a lot more efficient to run star with only 8
threads each.

**Comment by Hoohm** [comment]
That is something that I have noticed sometimes on local servers. Although that seemed to be reversed when using clusters.
