### ISSUE TITLE
generate-plot error

### ISSUE THREAD

**Issue by abmmki** [Hoohm/dropSeqPipe#5]
Hi,

I am using 0.23a version. At the generate-plot step it looks like all the required plots I got, however, I see error message at the end. Just wonder if I am missing anything? How to overcome this?

Plotting knee plots
There were 16 warnings (use warnings() to see them)
Plotting base stats
Loading required package: magrittr
`geom_smooth()` using method = 'loess'
`geom_smooth()` using method = 'loess'
`geom_smooth()` using method = 'loess'
`geom_smooth()` using method = 'loess'
`geom_smooth()` using method = 'loess'
`geom_smooth()` using method = 'loess'
`geom_smooth()` using method = 'loess'
`geom_smooth()` using method = 'loess'
`geom_smooth()` using method = 'loess'
`geom_smooth()` using method = 'loess'
`geom_smooth()` using method = 'loess'
`geom_smooth()` using method = 'loess'
`geom_smooth()` using method = 'loess'
`geom_smooth()` using method = 'loess'
`geom_smooth()` using method = 'loess'
`geom_smooth()` using method = 'loess'
Error in `[<-.data.frame`(`*tmp*`, i, 3, value = c(39858902L, 28250991L : 
  replacement has 2 rows, data has 1
Calls: plotBCDrop -> [<- -> [<-.data.frame
Execution halted
Traceback (most recent call last):
  File "/bin/dropSeqPipe", line 9, in <module>
    load_entry_point('dropSeqPipe==0.23a0', 'console_scripts', 'dropSeqPipe')()
  File "/usr/lib/python3.4/site-packages/dropSeqPipe/__main__.py", line 182, in main
    shell(base_summary)
  File "/usr/lib/python3.4/site-packages/snakemake-3.10.1-py3.4.egg/snakemake/shell.py", line 80, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'Rscript /usr/lib/python3.4/site-packages/dropSeqPipe/Rscripts/singleCell/rna_metrics.R /hd2/' returned non-zero exit status 1

# Thanks

**Comment by Hoohm** [comment]
Hello,
sadly the 0.23a version still has a whole Rscript for all of those plots so it's difficult to debug. This will be fixed in 0.24.
I guess the main issue is that one of the log files is probably empty. Maybe your filters are too loose.
Could you tell me which plot has been produced and which not?

**Comment by abmmki** [comment]
HI,

I got following 7 plots for each of my 16 samples, and none are empty.

SAMPLE_base_freq_plot.pdf   
SAMPLE_Cell_qual.pdf    
SAMPLE_knee_plot.pdf  
SAMPLE_polya_trimmed.pdf  
SAMPLE_rna_metrics.pdf
SAMPLE_SMART_trimmed.pdf
SAMPLE_UMI_qual.pdf

I also got fastqc.pdf plot. Just which is empty is Rplot.pdf file. .... and I think it is supposed to be empty (?).

best,

**Comment by Hoohm** [comment]
I see, you might be missing the BCDrop.pdf which is the summary of cell barcode and UMI filtering.
Did you run the fastqc step? You must have since you have the plot.
Could you please paste the config file?

**Comment by abmmki** [comment]
Yes, I run the fastqc step first. And got the FastQC plot pdf file.

# config.yaml

Samples:
    S1:
        fraction: 0.0001
        expected_cells: 350
    S2:
        fraction: 0.0001
        expected_cells: 400
    S3:
        fraction: 0.0001
        expected_cells: 400
    S4:
        fraction: 0.0001
        expected_cells: 900
    S5:
        fraction: 0.00005
        expected_cells: 1000
    S6:
        fraction: 0.00005
        expected_cells: 950
    S7:
        fraction: 0.00002
        expected_cells: 2000
    S8:
        fraction: 0.00005
        expected_cells: 900
    S9:
        fraction: 0.00005
        expected_cells: 1400
    S10:
        fraction: 0.00005
        expected_cells: 800
    S11:
        fraction: 0.0001
        expected_cells: 1000
    S12:
        fraction: 0.00002
        expected_cells: 2000
    S13:
        fraction: 0.00005
        expected_cells: 2300
    S14:
        fraction: 0.00002
        expected_cells: 1700
    S15:
        fraction: 0.00003
        expected_cells: 1800
    S16:
        fraction: 0.00003
        expected_cells: 2200
GENOMEREF: /home/bin/DropSeqMetaData/dmel.6.9.fa
REFFLAT: /home/bin/DropSeqMetaData/dmel.6.9.refFlat
METAREF: /home/bin/DropSeqMetaData/STAR_INDEX_NO_GTF
RRNAINTERVALS: /home/bin/DropSeqMetaData/dmel.6.9.rRNA.intervals
GTF: /home/bin/DropSeqMetaData/dmel.6.9.gtf
SPECIES:
    - DROSOPHILA
GLOBAL:
    5PrimeSmartAdapter: AAGCAGTGGTATCAACGCAGAGT
    data_type: singleCell
    allowed_aligner_mismatch: 10
    min_count_per_umi: 1
    Cell_barcode:
        start: 1
        end: 12
        min_quality: 10
        num_below_quality: 1
    UMI:
        start: 13
        end: 20
        min_quality: 10
        num_below_quality: 1

**Comment by abmmki** [comment]
would it be possible that I am missing it as I added following parameter in post_align.snak

VALIDATION_STRINGENCY=LENIENT\
