### ISSUE TITLE
The merge_single_counts.R step takes 60GB memory each and runs now for >30h.

### ISSUE THREAD

**Issue by grst** [Hoohm/dropSeqPipe#52]
Ist that normal behaviour?

**Comment by Hoohm** [comment]
Hey! I've noticed this happening sometimes. A major problem is the merge function in R. It's basically a full outer join but badly coded. Works well for low dimensions, bad with high ones and high number of samples.

One major update that is needed for dropSeqPipe is to convert all full matrices to parse ones and write to disk as [mtx format](https://math.nist.gov/MatrixMarket/formats.html).

This will decrease space usage and there are probably a few cool functions to merge samples together.

**Comment by Hoohm** [comment]
Fixed on the develop branch. Will be integrated to the next release
