### ISSUE TITLE
Generate Plot | Error in mmm 

### ISSUE THREAD

**Issue by abmmki** [Hoohm/dropSeqPipe#6]
Hi,

In generate-plot step I am getting following error. What I am mising?
Using 023a version.

Plotting knee plots
Warning messages:
1: Removed 716167 rows containing missing values (geom_point). 
2: Removed 563180 rows containing missing values (geom_point). 
3: Removed 1336568 rows containing missing values (geom_point). 
4: Removed 1230829 rows containing missing values (geom_point). 
5: Removed 1180851 rows containing missing values (geom_point). 
6: Removed 1473024 rows containing missing values (geom_point). 
Plotting base stats
Loading required package: magrittr
Error in mmm < each : comparison of these types is not implemented
Calls: plotRNAMetrics ... Reduce -> f -> rbind_gtable -> compare_unit -> unit -> comp
Execution halted
Traceback (most recent call last):
  File "/bin/dropSeqPipe", line 9, in <module>
    load_entry_point('dropSeqPipe==0.23a0', 'console_scripts', 'dropSeqPipe')()
  File "/usr/lib/python3.4/site-packages/dropSeqPipe/__main__.py", line 182, in main
    shell(base_summary)
  File "/usr/lib/python3.4/site-packages/snakemake-3.10.1-py3.4.egg/snakemake/shell.py", line 80, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'Rscript /usr/lib/python3.4/site-packages/dropSeqPipe/Rscripts/singleCell/rna_metrics.R /PROJECTS/' returned non-zero exit status 1

**Comment by abmmki** [comment]
just to add, I am using drosophila BDGP 6 version genome (with many new and uncharacterised chromosomes)

**Comment by duyck** [comment]
Here's a fix I created. This forces the gtables objects to take the "last" plots width as the width for both.

Edit file: 
${HOME}/.local/lib/python3.5/site-packages/dropSeqPipe/Rscripts/singleCell/rna_metrics.R

Replace: 
grid::grid.draw(rbind(gp1, gp2))  
with  
grid::grid.draw(rbind(gp1, gp2, size = "last"))

**Comment by abmmki** [comment]
@duyck 
Hi,
Many thanks. It worked perfectly.
Thanks once again.
