### ISSUE TITLE
I have issue on STAR running part. help!!!

### ISSUE THREAD

**Issue by Jun-Lizst** [Hoohm/dropSeqPipe#61]
It will generate some big index files when running snakemake map. How can I direct the index directory to snakemake,since I have build up the index on my own.

**Comment by Hoohm** [comment]
@Jun-NIBS As long as you store it where it's expected, the pipeline should recognize and use it.
Although, I would not recommend doing this. It's probably going to lead to small issues that are annoying to fix whereas just rerunning it through the pipeline will work automatically.

**Comment by Jun-Lizst** [comment]
Thanks for answer.
I’ll try.

Best
Jun

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Patrick Roelli <notifications@github.com>
发送时间: Friday, November 16, 2018 7:28:42 PM
收件人: Hoohm/dropSeqPipe
抄送: Jun; Mention
主题: Re: [Hoohm/dropSeqPipe] I have issue on STAR running part. help!!! (#61)


@Jun-NIBS<https://github.com/Jun-NIBS> As long as you store it where it's expected, the pipeline should recognize and use it.
Although, I would not recommend doing this. It's probably going to lead to small issues that are annoying to fix whereas just rerunning it through the pipeline will work automatically.

―
