### ISSUE TITLE
Consider a minimal repeated tutorial

### ISSUE THREAD

**Issue by Puriney** [Hoohm/dropSeqPipe#64]
Could you please consider preparing a minimal repeated example to help the new users better use the pipeline, as *This package is trying to be as user friendly as possible.*

I noticed some issues (#60 #61 #62 #63) are probably from some new users. Hope the minimal example could probably help them identify the technical errors, e.g., environment settings, and access to tools.

**Comment by Hoohm** [comment]
Hello @Puriney 

I agree a small tutorial would be helpful.


There is a major version coming out soon (one or two weeks, see develop branch) which will change quite a bit of functionality and usability of the pipeline. Once this is out, I will provide more information on the docs on how to use it.

**Comment by Puriney** [comment]
Looking forward to it.
