### ISSUE TITLE
generate-meta |  UnboundLocalError: local variable 'samples_yaml' referenced before assignment

### ISSUE THREAD

**Issue by abmmki** [Hoohm/dropSeqPipe#7]
Hi,

I got following error in generate meta step with mouse Ensembl Grcm38 genome and its gtf file.
Log.out file shows that all steps completed (it says "done  ..... finished successfully 
DONE: Genome generation, EXITING)
It looks like I have all necessary file generated (not sure though if incomplete)

I just wonder how to fix this error:

[Sun Oct 22 22:23:13 CDT 2017] org.broadinstitute.dropseqrna.annotation.CreateIntervalsFiles SEQUENCE_DICTIONARY=mm38.dict REDUCED_GTF=mm38_reduced.gtf OUTPUT=. PREFIX=mm38    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json

[Sun Oct 22 22:23:18 2017] Finished job 1.
[Sun Oct 22 22:23:18 2017] 5 of 6 steps (83%) done
[Sun Oct 22 22:23:18 2017] 
[Sun Oct 22 22:23:18 2017] localrule all:
    input: mm38.rRNA.intervals, STAR_INDEX_NO_GTF/SA
    jobid: 0
[Sun Oct 22 22:23:18 2017] 
[Sun Oct 22 22:23:18 2017] Finished job 0.
[Sun Oct 22 22:23:18 2017] 6 of 6 steps (100%) done
Traceback (most recent call last):
  File "/bin/dropSeqPipe", line 9, in <module>
    load_entry_point('dropSeqPipe==0.23a0', 'console_scripts', 'dropSeqPipe')()
  File "/usr/lib/python3.4/site-packages/dropSeqPipe/__main__.py", line 96, in main
    if(samples_yaml['GLOBAL']['data_type'] not in ['singleCell', 'bulk']):
UnboundLocalError: local variable 'samples_yaml' referenced before assignment

**Comment by Hoohm** [comment]
The meta_generation works fine. This is just a tab bug that was fixed in the newer version. 0.24
Are you sure you are using 0.24?
`load_entry_point('dropSeqPipe==0.23a0', 'console_scripts', 'dropSeqPipe')()`

**Comment by abmmki** [comment]
Hi,

Thanks. I am using 23a version. So, v0.24 will solve.

thanks again
