### ISSUE TITLE
KeyError for 'barcode-whitelist'

### ISSUE THREAD

**Issue by abmmki** [Hoohm/dropSeqPipe#81]
# I am getting following error, irrespective of I have file name or not having any name of barcode-whitelist:

KeyError in line 22 of /home/bin/dropSeqPipe/Snakefile:
'barcode-whitelist'
  File "/home/bin/dropSeqPipe/Snakefile", line 22, in <module>

# From config file, I also tried deleting the parameter line: "barcode-whitelist:" 
but didn't work.
Version 0.4 using. 

Let me know what I am missing
thanks

**Comment by abmmki** [comment]
I see the problem.
in config.yaml with would be 'barcode-whitelist', not with underscore 'barcode_whitelist'

Also, read_length in sample.csv file, not "read_lengths"
This extra (s) creating problem

**Comment by Hoohm** [comment]
Hello @abmmki 
I guess we should release a new version with those small fixes. They are actually already on the master branch.
