### ISSUE TITLE
limitGenomeGenerateRAM=31000000000

### ISSUE THREAD

**Issue by abmmki** [Hoohm/dropSeqPipe#82]
EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=31000000000is too small for your genome
SOLUTION: please specify limitGenomeGenerateRAM not less than85544254848 and make that much RAM available 

# Using Version 0.4.  Which file to change or how to provide this parameter?? I can provide more RAM or delete this parameter. But how or in which file?

# also where is:    prep_star.py     file?

thanks

**Comment by Hoohm** [comment]
Hello @abmmki 
this is strange because this was changed a while ago on the [latest master branch](https://github.com/Hoohm/dropSeqPipe/blob/fc78da72f4a50496519c13ed19633a1825b01b0b/rules/generate_meta.smk#L137).

Could you maybe download master branch and try again?

**Comment by abmmki** [comment]
It didn't help. So, I edited the file "generate_meta.smk", and added following (        --limitGenomeGenerateRAM 999999999999999999\)


    conda: '../envs/star.yaml'
    shell:
        """mkdir -p {params.genomeDir}; STAR\
        --runThreadN {threads}\
        --limitGenomeGenerateRAM 999999999999999999\
	--runMode genomeGenerate\
        --genomeDir {params.genomeDir}\
        --genomeFastaFiles {input.reference_file}\
        --sjdbGTFfile {input.annotation_file}\
        --sjdbOverhang {params.sjdbOverhang}\
        --genomeChrBinNbits {params.genomeChrBinNbits}
        """

>>> that worked file

**Comment by Hoohm** [comment]
Great, that's what I would have proposed to do in the end.
