### ISSUE TITLE
No rule to produce meta

### ISSUE THREAD

**Issue by abmmki** [Hoohm/dropSeqPipe#85]
Trying to download and generate Meta-data  using following command

snakemake --cores 16 meta --use-conda --directory ~/PROJECTS/Dropseq16

~/.conda/envs/myconda/lib/python3.6/site-packages/snakemake/workflow.py:70: FutureWarning: read_table is deprecated, use read_csv instead.

  self._workdir = None
Building DAG of jobs...
MissingRuleException:
No rule to produce meta (if you use input functions make sure that they don't raise unexpected exceptions).

# Ensembl file location
ftp://ftp.ensembl.org/pub/release-90/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.dna.toplevel.fa.gz

# I need to manually edit the "download_meta_single.smk" file to have correct FTP site pattern
# am I missing something ? Why I am getting such error

thanks

**Comment by Hoohm** [comment]
Hello @abmmki 

This rule doesn't exist anymore, the doc has to be updated.

It is now called: `download_meta`

Let me know if this works

**Comment by Hoohm** [comment]
I assume it worked. Closing this
