### ISSUE TITLE
Locus extraction for Introns

### ISSUE THREAD

**Issue by JaydeepBhat** [Hoohm/dropSeqPipe#87]
I am interested in getting read counts for introns in the final extraction matrix. As per dropseq pipeline (v0.4), I used "INTRON" together with "CODING" and "UTR" in the config.yaml file. Unfortunately, I am getting following error:

**Error**
drop-seq-pipe_1  | INFO 2019-09-23 20:37:47     SingleCellRnaSeqMetricsCollector
drop-seq-pipe_1  |
drop-seq-pipe_1  | ********** NOTE: Picard's command line syntax is changing.
drop-seq-pipe_1  | **********
drop-seq-pipe_1  | ********** For more information, please see:
drop-seq-pipe_1  | ********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
drop-seq-pipe_1  | **********
drop-seq-pipe_1  | ********** The command line looks like this in the new syntax:
drop-seq-pipe_1  | **********
drop-seq-pipe_1  | **********    SingleCellRnaSeqMetricsCollector -INPUT /output/results/samples/MMus_nuc_fresh_rep2/final.bam -OUTPUT /output/results/logs/dropseq_tools/MMus_nuc_fresh_rep2_rna_metrics.txt -ANNOTATIONS_FILE /ref/mus_musculus_38_91/curated_annotation.refFlat -CELL_BC_FILE /output/results/samples/MMus_nuc_fresh_rep2/barcodes.csv -RIBOSOMAL_INTERVALS /ref/mus_musculus_38_91/annotation.rRNA.intervals
drop-seq-pipe_1  | **********
drop-seq-pipe_1  |
drop-seq-pipe_1  |
drop-seq-pipe_1  | ERROR: 'INTRON' is not a valid value for LocusFunction.
drop-seq-pipe_1  |
drop-seq-pipe_1  | ERROR: 'INTRON' is not a valid value for LocusFunction.
drop-seq-pipe_1  |
drop-seq-pipe_1  | 20:37:47.985 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/output/results/.snakemake/conda/825df543/share/dropseq_tools-2.0.0-0/jar/lib/picard-2.18.14.jar!/com/intel/gkl/native/libgkl_compression.so
drop-seq-pipe_1  | USAGE: DigitalExpression [options]

**Question:** Is it really possible to generate read counts for introns by using locus extraction using new pipeline? or Is it a bug? or something I am doing wrong? Please let me know!
Thank you.

**Comment by Hoohm** [comment]
Hello @JaydeepBhat 
This is because there is a mistake in the documentation, it's supposed to be INTRONIC and not INTRON. Good catch! Thanks

I'll change it in the next release.

**Comment by JaydeepBhat** [comment]
Thank you so much. It's working fine for INTRONIC.
