### ISSUE TITLE
Hi, i have a question about using dropSeqPipe

### ISSUE THREAD

**Issue by kkjjhhk** [Hoohm/dropSeqPipe#9]
Hi, 

I'm doing follow the wiki and, 

have a problem in generate-meta step.

here is error massages : 

[Mon Oct 30 19:16:47 2017] IndexError in line 5 of /usr/lib/python3.6/site-packages/dropSeqPipe/Snakefiles/generate_meta.snake:
[Mon Oct 30 19:16:47 2017] list index out of range
[Mon Oct 30 19:16:47 2017]   File "/usr/lib/python3.6/site-packages/dropSeqPipe/Snakefiles/generate_meta.snake", line 5, in <module>
Traceback (most recent call last):
  File "/usr/bin/dropSeqPipe", line 11, in <module>
    load_entry_point('dropSeqPipe==0.23a0', 'console_scripts', 'dropSeqPipe')()
  File "/usr/lib/python3.6/site-packages/dropSeqPipe/__main__.py", line 81, in main
    complementory_args))
  File "/usr/lib/python3.6/site-packages/snakemake/shell.py", line 100, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' set -euo pipefail;  snakemake -s /usr/lib/python3.6/site-packages/dropSeqPipe/Snakefiles/generate_meta.snake --cores 5 -pT -d ../../hg19_dropseqpipe --configfile ./config.yaml ' returned non-zero exit status 1.

and this is my config.yaml:

config.yaml

Samples:
    SRR5250848:
        fraction: 0.001
        expected_cells: 100
GENOMEREF: /storage/hd2/jina/Homo_sapiens/UCSC/hg19/Sequence/WholeGenomeFasta/genome.fa
REFFLAT: /storage/hd2/jina/Homo_sapiens/UCSC/hg19/Annotation/Genes/refFlat.txt
METAREF: /storage/hd2/jina/hg19_STAR/
RRNAINTERVALS: /storage/hd2/jina/Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.rRNA.interval_list
GTF: /storage/hd2/jina/Homo_sapiens/UCSC/hg19/Annotation/Genes/genes.gtf
SPECIES:
    - HUMAN
CORES: 5
GLOBAL:
    5PrimeSmartAdapter: CACACTCTTTCCCTACACGACGC
    data_type: SingleCell
    allowed_aligner_mismatch: 10
    min_count_per_umi: 1
    Cell_barcode:
        start: 1
        end: 12
        min_quality: 10
        num_below_quality: 1
    UMI:
        start: 13
        end: 20
        min_quality: 10
        num_below_quality: 1

can you tell me about which commend is wrong?

thanks,

**Comment by Hoohm** [comment]
Hello,

this is probably linked to a wrong genome file extension.
In the folder containing the genome and the annotation you should have exactly two files:
One file is the genome and has to end in .fa
The second is the annotation file and has to end with .gtf

That should fix it.

**Comment by Hoohm** [comment]
@kkjjhhk Could you fix it? Can I close the issue?

**Comment by kkjjhhk** [comment]
Yes, I fixed it. 

 

Thanks and have a nice day!
