### ISSUE TITLE
NH tag not found in BAM file

### ISSUE THREAD

**Issue by abmmki** [Hoohm/dropSeqPipe#98]
HI,
previous mereging script not keeping NH tags. New version is OK.
Also, deleting "temp" prefix from *.smk files keeps all files intermediate files including wide format expression metrix.

best,

**Comment by abmmki** [comment]
map.smk  is producing Aligned.out.bam  file which keeps NH tag, but in later step: MergeBamAlignment
produces Aligned.merged.bam where NH tag is deleted. How to keep this tag here and also in later stages gene_exon_tagged.bam  and final.bam file.

In map.smk or in the script merge_bam.py where need to change to keep the NH tag??
This is needful for velocyto (http://velocyto.org/) run.

Thanks for any suggestion.

best,

**Comment by Hoohm** [comment]
Yes, the latest version fixed this issue.

There is an option to keep all temp files `--no-temp`
